# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-09 18:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='employer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('employer_id', models.IntegerField(blank=True, null=True)),
                ('message_id', models.IntegerField(blank=True, null=True)),
                ('starred', models.CharField(max_length=30)),
                ('selected', models.FilePathField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='seeker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('seeker_id', models.IntegerField(blank=True, null=True)),
                ('message_id', models.IntegerField(blank=True, null=True)),
                ('last_resume_date', models.DateField()),
                ('resume', models.FilePathField()),
                ('video', models.FilePathField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
